{% set name = "roseau-load-flow" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/roseau_load_flow-{{ version }}.tar.gz
  sha256: 4100944723ba43efd8ac78046cda91965554e720652dc6b6f3b243a02f17201c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.9,<4.0
    - numpy >=1.21.5
    - pandas >=1.4.0
    - geopandas >=0.10.2
    - shapely >=2.0.0
    - regex >=2022.1.18
    - requests >=2.28.1
    - pint >=0.19.2

test:
  imports:
    - roseau
    - roseau.load_flow
    - roseau.load_flow.io
    - roseau.load_flow.models
    - roseau.load_flow.utils
  commands:
    - pip check
  requires:
    - pip


about:
  home: https://github.com/RoseauTechnologies/Roseau_Load_Flow/
  summary: Three-phase load flow solver
  license: BSD-3-Clause
  license_file: LICENSE.md
  summary: Highly capable three-phase load flow solver of Roseau Technologies.
  doc_url: https://roseautechnologies.github.io/Roseau_Load_Flow/


extra:
  recipe-maintainers:
    - benoit9126
